/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import dao.DAO;
import dao.EmployeeDao;
import java.awt.Color;
import model.Employee;

/**
 *
 * @author NamNguyen
 */
public class LoginFrm extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrm
     */
    public LoginFrm() {
        super("Login");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jUsernameField = new javax.swing.JTextField();
        jUsernameLabel = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jPassLabel = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUsernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUsernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsernameFieldFocusLost(evt);
            }
        });
        jPanel2.add(jUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 201, 40));

        jUsernameLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameLabel.setText("Username");
        jPanel2.add(jUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 40));

        jPasswordField.setText("jPasswordField1");
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });
        jPanel2.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 201, 40));

        jPassLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jPassLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPassLabel.setText("Password");
        jPanel2.add(jPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Download\\rsz_mpctc3pcta0n-hpctc3pctacnh-onyx-cinema-led-e1544440515817.jpg")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (jUsernameField.getText().equals("Enter User Name")) {
            jUsernameField.requestFocus();
        } else if (String.valueOf(jPasswordField.getPassword()).equals("Enter Password")) {
            jPasswordField.requestFocus();
        } else {
            Employee em = new Employee();
            em.setUsername(jUsernameField.getText());
            em.setPassword(jPasswordField.getText());

            EmployeeDao ed = new EmployeeDao();
            if (ed.checkLogin(em)) {
                if (em.getPosition().replaceAll("\\s","").equalsIgnoreCase("manager")) {
                    (new ManageHomeFrm(em)).setVisible(true);
                    this.dispose();
                } else if (em.getPosition().replaceAll("\\s","").equalsIgnoreCase("seller")) {
                    (new SellerHomeFrm()).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "The function of the role " + em.getPosition().replaceAll("\\s","") + " is under construction!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect username and/or password!");
            }
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void jUsernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFieldFocusGained
        if (jUsernameField.getText().trim().equals("Enter User Name")) {
            jUsernameField.setText("");
        }
        jUsernameField.setForeground(Color.BLACK);
    }//GEN-LAST:event_jUsernameFieldFocusGained

    private void jUsernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFieldFocusLost
        if (jUsernameField.getText().trim().equals("")) {
            jUsernameField.setText("Enter User Name");
        }
        jUsernameField.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jUsernameFieldFocusLost

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
         
            jPasswordField.setText("");
        
        

        jPasswordField.setForeground(Color.BLACK);
    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
        if (String.valueOf(jPasswordField.getPassword()).trim().equals("")) {
            jPasswordField.setText("Enter Password");
        }
        jPasswordField.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jPasswordFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jPassLabel;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jUsernameField;
    private javax.swing.JLabel jUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
